//------------------------------------------------------------------------------
// <auto-generated>
//     Ce code a été généré à partir d'un modèle.
//
//     Des modifications manuelles apportées à ce fichier peuvent conduire à un comportement inattendu de votre application.
//     Les modifications manuelles apportées à ce fichier sont remplacées si le code est régénéré.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Système_de_Gestion_des_Étudiants
{
    using System;
    using System.Collections.Generic;
    
    public partial class Notes
    {
        public int Id { get; set; }
        public Nullable<int> IdEtudiant { get; set; }
        public Nullable<int> IdMatiere { get; set; }
        public double Note { get; set; }
    
        public virtual Etudiants Etudiants { get; set; }
        public virtual Matieres Matieres { get; set; }
    }
}
